version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD

  app:
    build: ./skeleton
    ports:
    - 8000:8000
    environment:
      POSTGRES_ADDRESS: "host=db port=5432 user=postgres password=DB_PASSWORD dbname=postgres sslmode=disable"
      AUTH_ADDRESS: "http://auth:8000/validate"
    depends_on:
      - db
      - auth
    restart: unless-stopped

  auth:
    build: ./authentication
    ports:
    - 8001:8000
    environment:
      POSTGRES_ADDRESS: "host=db port=5432 user=postgres password=DB_PASSWORD dbname=postgres sslmode=disable"
      TOKEN_LENGTH: "64"
      ACCESS_TOKEN_LIFETIME: "5m"
      REFRESH_TOKEN_LIFETIME: "10m"
      CONFIRMATION_TOKEN_LIFETIME: "24h"
      MESSAGE_QUEUE_ADDRESS: "amqp://guest:guest@rabbit-mq:5672/"
    depends_on:
      - db
      - rabbit-mq
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672
    restart: unless-stopped

  notifier:
    build: ./notification
    environment:
      MESSAGE_QUEUE_ADDRESS: "amqp://guest:guest@rabbit-mq:5672/"
      SMS_HOST: "https://sms.ru"
      SMS_API_ID: "${SMS_API_ID}"
    depends_on:
      - rabbit-mq
    restart: unless-stopped