version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD

  app:
    build:
      context: ./
      dockerfile: Dockerfile-main
      args:
        service_name: skeleton
    ports:
    - 8000:8000
    environment:
      POSTGRES_ADDRESS: "host=db port=5432 user=postgres password=DB_PASSWORD dbname=postgres sslmode=disable"
      AUTH_ADDRESS: "auth:5300"
    depends_on:
      - db
      - auth
    restart: unless-stopped

  auth:
    build:
      context: ./
      dockerfile: Dockerfile-main
      args:
        service_name: authentication
    ports:
    - 8001:8000
    environment:
      POSTGRES_ADDRESS: "host=db port=5432 user=postgres password=DB_PASSWORD dbname=postgres sslmode=disable"
      TOKEN_LENGTH: "64"
      ACCESS_TOKEN_LIFETIME: "5m"
      REFRESH_TOKEN_LIFETIME: "10m"
      CONFIRMATION_TOKEN_LIFETIME: "24h"
      MESSAGE_QUEUE_ADDRESS: "amqp://guest:guest@rabbit-mq:5672/"
    depends_on:
      - db
      - rabbit-mq
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672
    restart: unless-stopped

  notifier:
    build:
      context: ./
      dockerfile: Dockerfile-main
      args:
        service_name: notification
    environment:
      MESSAGE_QUEUE_ADDRESS: "amqp://guest:guest@rabbit-mq:5672/"
      SMS_HOST: "https://sms.ru"
      SMS_API_ID: "${SMS_API_ID}"
    depends_on:
      - rabbit-mq
    restart: unless-stopped

  importer:
    build:
      context: ./
      dockerfile: Dockerfile-main
      args:
        service_name: importer
    depends_on:
      - rabbit-mq
      - db
    environment:
      MESSAGE_QUEUE_ADDRESS: "amqp://guest:guest@rabbit-mq:5672/"
      POSTGRES_ADDRESS: "host=db port=5432 user=postgres password=DB_PASSWORD dbname=postgres sslmode=disable"
    restart: unless-stopped

  uploader:
    build:
      context: ./
      dockerfile: Dockerfile-main
      args:
        service_name: uploader
    ports:
    - 8002:8000
    depends_on:
      - rabbit-mq
    environment:
      MESSAGE_QUEUE_ADDRESS: "amqp://guest:guest@rabbit-mq:5672/"
      BATCH_SIZE: "500"
      AUTH_ADDRESS: "auth:5300"
    restart: unless-stopped